### ISSUE TITLE
Add more points for "What's new in this guide" on start page?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#258]
**Status**: decision required

## question / decisions

* [ ] should new things / recently documented things still be announced on the start page of "Writing documentation"?

![image](https://user-images.githubusercontent.com/13206455/171877794-961d3084-3f58-472d-b5ca-a5a22561ece4.png)

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Index.html

* [ ] where should information about new things be announced (e.g. on typo3.org, twitter?)
* [x] the "What's new" page is quite old - decide if should be used further to announce new things or be removed: #287 
 
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WhatsNew.html#whats-new

## Possibly add links to these new things

if "What's new in this guide" on start page should be maintained.

- [x] plantUml
- [x] automatic screenshots
- [ ] card layout, see also #254
- [ ] confval, see also #255
- [ ] set up GitHub actions?

**Comment by linawolf** [comment]
We removed the section as none was keeping it up to date
