### ISSUE TITLE
Update / merge / add links: in other manuals

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#5]
There are chapters / sections in other manuals, where documentation is documented. Some of it is outdated. 

# todo

* To help maintainability: documentation about documentation can be maintained in one place (this guide). Information in other manuals should be updated, reduced or deleted and links to this guide added.

# github.com/TYPO3-Documentation

* [x] https://docs.typo3.org/Contribute/Index.html
* [x] https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-RenderTypo3Documentation ?
* [x] https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/Documentation/Index.html
* [x] https://docs.typo3.org/Tips/TipOfTheDay/Index.html#how-to-start-documentation-for-your-typo3-extension
* [x] startpage: https://docs.typo3.org/ : Quickstart extension documentation
* [x] [Example extension manual](https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual)
* [x] https://docs.typo3.org/Tips/DocumentationWriters/Index.html
* [x] https://docs.typo3.org/Tips/DocumentationWriters/Extensions/Index.html

# external

* [x] add information about Docker to section on rendering? https://typo3worx.eu/2017/02/guide-to-typo3-documentation-part-3-contribute/ (added link to "Writing Documentation" as comment)
