### ISSUE TITLE
Optimize and agree on image icons

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#61]
This is about creating images with arrows, boxes, numbers etc. for highlighting things. See also initial issue #11: "Add guidelines for images" (closed).

# Status quo

We created ["Guidelines for Images"](https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/GuidelinesForImages.html) and design team supplied [some sample icons](https://github.com/TYPO3-Documentation/images/blob/master/design-team/icons_preview/Images.rst).

# Problems

We should further refine icons and sample images because:

* [ ] color scheme of icons clash with orange used in documentation, choose different color? (see ([t3docstheme issue #110](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/110)), see https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/79#issuecomment-649456510
* [ ] Using flat arrows doesn't look so great - question do we need arrows, for example this images uses a drop as combination of a pointing device and a number
* [ ] placing the numbers with rounded edges next to boxes with rounded edges does not look so great or is difficult to get right, especially if the rectangle has rounded edges

## todos

* [ ] decide on colors
* [ ] decide on shapes
* [ ] make sample shapes easier to use (e.g. import into graphics tool) - it is possible to create one SVG including all images and import them for example in Inkscape - https://softwarerecs.stackexchange.com/questions/74442/workflow-and-tools-to-augment-screenshots-with-custom-arrows-numbers-boxes-etc/74602#74602

**Comment by sypets** [comment]
Using a drop shadow with images looks better:

![edit_me_on_github](https://user-images.githubusercontent.com/13206455/55279617-c1f7ac00-531a-11e9-95e2-fe97142b65e0.png)


![edit_me_on_github2_shadow](https://user-images.githubusercontent.com/13206455/55279646-0e42ec00-531b-11e9-83de-ed5eae634b8b.png)

Also, some alternatives with boxes and numbers:

![backend-with-boxes](https://user-images.githubusercontent.com/13206455/55279912-d8a00200-531e-11e9-9471-a295eb693bd1.png)

![backend-boxes2](https://user-images.githubusercontent.com/13206455/55279921-ee152c00-531e-11e9-8596-4b43cfdac32a.png)

![backend-boxes2+shadow](https://user-images.githubusercontent.com/13206455/55279943-2157bb00-531f-11e9-993c-2362fe8f2abf.png)

**Comment by sypets** [comment]
This is the repo for the images: https://github.com/TYPO3-Documentation/images

**Comment by susannemoog** [comment]
Hey, thanks for your work here, I would close this issue in favour of all the work that has been done on automating the screenshots and annotations. I trust in the work they are doing there and will gladly use the styling they define in their project. The more screenshots will be automated, the easier it will then be to change / adjust the styling afterwards. For now, let's concentrate on getting that done.
